dbt_core:
  outputs:
    prd:
      dataset: dbt_core
      job_execution_timeout_seconds: 900
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: "sandbox-cmartins"
      threads: 30
      type: bigquery
    dev:
      dataset: dbt_core
      job_execution_timeout_seconds: 900
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: "sandbox-cmartins"
      threads: 30
      type: bigquery